# Generated by Django 5.1.2 on 2024-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
