# Generated by Django 5.1.2 on 2024-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_course_student_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='crud_images/'),
        ),
    ]
